apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: busybox
    image: busybox
    command: ["sleep"]
    args: ["infinity"]
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
