apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller-debug-deployment
  namespace: default
  labels:
    app: admission-controller-debug-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller-debug-deployment
  template:
    metadata:
      labels:
        app: admission-controller-debug-deployment
    spec:
      containers:
      - name: go-container
        image: golang
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 443
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
