apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-validation
webhooks:
  - name: pod-validation.default.com
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    clientConfig:
      service:
        name: admission-server
        namespace: default
        path: /validate/
      caBundle: "${CA_BUNDLE}"
